export default [
  `It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife`,
  `Happy families are all alike; every unhappy family is unhappy in its own way`,
  `It was a bright cold day in April, and the clocks were striking thirteen`,
  `Someone must have slandered Josef K., for one morning, without having done anything truly wrong, he was arrested`,
  `You are about to begin reading Italo Calvinos new novel, If on a winters night a traveler`,
  `this moocow that was coming down along the road met a nicens little boy named baby tuckoo`,
  `she, Oedipa, had been named executor, or she supposed executrix, of the estate of one Pierce Inverarity`,
  `Through the fence, between the curling flower spaces, I could see them hitting`,
  `Mrs. Dalloway said she would buy the flowers herself`,
  `I was the shadow of the waxwing slain By the false azure in the windowpane`,
  `Ships at a distance have every mans wish on board`,
  `There was a boy called Eustace Clarence Scrubb, and he almost deserved it`,
  `arbitrarily one chooses that moment of experience from which to look back or from which to look ahead`,
  `Miss Brooke had that kind of beauty which seems to be thrown into relief by poor dress`,
  `The towers of Zenith aspired above the morning mist; austere towers of steel and cement and limestone, sturdy as cliffs and delicate as silver rods`,
  `Many years later, as he faced the firing squad, Colonel Aureliano Buendía was to remember that distant afternoon when his father took him to discover ice`,
  `Mother died today. Or maybe yesterday; I cant be sure`,
  `Stately, plump Buck Mulligan came from the stairhead, bearing a bowl of lather on which a mirror and a razor lay crossed`,
  `The first time I laid eyes on Terry Lennox he was drunk in a Rolls Royce Silver Wraith outside the terrace of the Dancers`,
  `Christmas wont be Christmas without any presents, grumbled Jo, lying on the rug`,
  `The sky above the port was the color of television, tuned to a dead channel.`,
  `Most really pretty girls have pretty ugly feet, and so does Mindy Metalman, Lenore notices, all of a sudden.`,
  `riverrun, past Eve and Adams, from swerve of shore to bend of bay, brings us by a commodius vicus of recirculation back to Howth Castle and Environs`
];